# Exception

try:
    x = 10 / 0
except:
    print("Something went wrong!")